### ISSUE TITLE
use aws configuration files

### ISSUE THREAD

**Issue by otakup0pe** [otakup0pe/awsswitch#1]
Instead of using a custom `aws.yml` file, just read from `~/.aws/config` / `~/.aws/credentials`. Keep the old behavior via a config flag or something maybe ❓

**Comment by otakup0pe** [comment]
hey @shaiguitar let me know if this is what you were thinking

**Comment by shaiguitar** [comment]
Yep. Haven't tested your commit, but ideally I don't need to write any additional files. All the aws info is already in those aforementioned files.

**Comment by otakup0pe** [comment]
Let me know if it works for you, I tested it with my local setup and it was fine.

**Comment by shaiguitar** [comment]
Did a git pull of `~/src/awsswitch` to 398d0698b34f07b95a49ca10c4e00169d5b71a1a and it seems it's still trying to look for the yml file, but since I don't have one, it fails. I think the gist of how this should work is

- Don't assume yml file. Work w/out one.
- Grab all creds from the awscli formats and turn those into the env vars necessary.

```
shai@lappy ~   % set -x
...
+-zsh:3> awsswitch FOOBAR
+awsswitch:2> local AWS=FOOBAR
+awsswitch:3> [ -z FOOBAR ']'
+awsswitch:6> [ FOOBAR '==' none ']'
+awsswitch:9> grep --color -e FOOBAR /Users/shai/.aws.yml
+awsswitch:10> echo 'invalid aws'
invalid aws
```

**Comment by otakup0pe** [comment]
I didn't change the default behavior. I guess it makes sense to change the default.

**Comment by rojomisin** [comment]
I have only 2 env vars set since I only want to try and pull from the credentials ini format in `~/.aws/credentials`

```
$ env | grep -i awsswitch
AWSSWITCH_CONFIG=awscli
PWD=/Users/rmicone/Dev/awsswitch
AWSSWITCH_PATH=/Users/rmicone/Dev/awsswitch

$ ./awsswitch.sh REDACTED
NOPE

```
keep getting `NOPE` 😢

**Comment by shaiguitar** [comment]
You need to try #2 - that hasn't been merged to master yet.

**Comment by otakup0pe** [comment]
This is now the only way awsswitch rolls. Open a new issue if things are broken.
